Api endpoints unit tests
ZihengSun/Geoweaver pull request #29
Opened 2022-01-09 11:22 UTC by uhhmed

2022-01-09 21:55 UTC, ZihengSun requested changes

2022-01-09 21:55 UTC, ZihengSun commented on src/test/java/com/gw/EnvironmentTest.java
> +    void testListHostWithEnvironments() throws Exception {
This test fails using the new `application.properties` under `test/resources`

2022-01-09 21:55 UTC, ZihengSun commented on src/test/java/com/gw/HelperMethods.java
> +public abstract class HelperMethods {
Since this is an abstract class. The class name should indicate that as well. Recommend to use `AbstractHelperMethodsTest`

2022-01-09 21:55 UTC, ZihengSun commented on src/test/java/com/gw/PythonTest.java
This test will fail on old version of h2. Should add new `application.properties` in `test/resources` and make it in `create-drop` mode to avoid the mess caused by h2 version conflicts.

2022-01-09 21:55 UTC, ZihengSun commented on src/test/resources/add_ssh_host.txt
> +type=host&hostname=New+Host&hostip=0.0.0.0&hostport=22&url=&hosttype=ssh&username=test&confidential=FALSE&ownerid=111111
just curious, why 0.0.0.0? I think it would be better to change to 127.0.0.1 which can actually be used.

2022-01-09 21:56 UTC, ZihengSun commented on src/test/java/com/gw/EnvironmentTest.java
> +    void testListHostWithEnvironments() throws Exception {
Make sure there is at least one host before running this test.

2022-01-10 13:34 UTC, uhhmed commented on src/test/java/com/gw/EnvironmentTest.java
> +    void testListHostWithEnvironments() throws Exception {
This has been resolved in latest commit.

2022-01-10 13:35 UTC, uhhmed commented on src/test/java/com/gw/HelperMethods.java
> +public abstract class HelperMethods {
This has been changed to reflect the recommend class name.

2022-01-10 13:36 UTC, uhhmed commented on src/test/java/com/gw/PythonTest.java
The new `application.properties` in the `test/` directory resolves this with the latest commit.

2022-01-10 13:38 UTC, uhhmed commented on src/test/resources/add_ssh_host.txt
> +type=host&hostname=New+Host&hostip=0.0.0.0&hostport=22&url=&hosttype=ssh&username=test&confidential=FALSE&ownerid=111111
This was added just to verify one of the tests reflecting the change in this file. This is updated to have 127.0.0.1 as IP in latest commit.

2022-01-12 01:41 UTC, ZihengSun approved these changes

2022-01-12 01:43 UTC, merged