update host.md
ZihengSun/Geoweaver pull request #31
Opened 2022-01-12 13:11 UTC by uhhmed

2022-01-12 22:21 UTC, ZihengSun requested changes

2022-01-12 22:21 UTC, ZihengSun commented on docs/host.md
> +1. Click the second icon from the left (python icon) at the bottom right corner of the "Host Details" page.
```suggestion
1. Click the python icon button in the toolbar of the shown "Host Details" page.
```

2022-01-12 22:21 UTC, ZihengSun commented on docs/host.md
How do people see the "Host Details" page?

2022-01-12 22:21 UTC, ZihengSun commented on docs/host.md
> +2. Input the `Host User Password` of your account on the server in the shown dialog pop up.
What about the Localhost? Where do they find password for localhost?

2022-01-12 22:21 UTC, ZihengSun commented on docs/host.md
> +3. An "Environment List" section will appear below the "Host Details" section showing all the available python environments on the connected server.
Are they really `all` available environments? Does it read both `pipenv` and `conda`? what about `virtualenv`?

2022-01-12 22:21 UTC, ZihengSun commented on docs/host.md
> +1. Click the second icon from the right (next to the red minus button) in the "Host Details" page.
Same problem. How do people access the `Host Details`.

2022-01-12 22:21 UTC, ZihengSun commented on docs/host.md
> +1. Click the second icon from the right (next to the red minus button) in the "Host Details" page.
```suggestion
1. Click the sitemap icon (the one with branches) button in the "Host Details" toolbar.
```

2022-01-12 22:21 UTC, ZihengSun commented on docs/host.md
> +2. Input the `Host User Password` of your account on the server in the shown dialog pop up.
Same problem as above.

2022-01-12 22:21 UTC, ZihengSun commented on docs/host.md
> +3. Click Confirm.
What happens after `confirm`? How do people know they do it right?

2022-01-12 22:21 UTC, ZihengSun commented on docs/host.md
> +1. Click the upload file icon (the middle icon) at the bottom right corner of the "Host Details" page.
```suggestion
1. Click the uploader icon button in the "Host Details" toolbar.
```

2022-01-12 22:21 UTC, ZihengSun commented on docs/host.md
> +2. Input the `Host Password` of your account on the server in the shown dialog pop up.
same

2022-01-12 22:21 UTC, ZihengSun commented on docs/host.md
> +3. A file upload section will appear below the "Host Details" section with drag and drop or file browser capability.
Better have a screenshot.

2022-01-12 22:21 UTC, ZihengSun commented on docs/host.md
> +4. Choose the desired file to upload, and click the start button below the "File Uploader Section" to initiate the upload.
```suggestion
4. Click on the `Open the File Browser` button to choose files, and click `Start` to initiate the uploading.
```

2022-01-12 22:21 UTC, ZihengSun commented on docs/host.md
> +5. A progress bar with a status above will indicate the progress of the upload.
What is next? What happens when uploading finishes? Where did the file go? 

A tutorial should have beginning and end. Don't leave without giving people an end.

2022-01-12 22:21 UTC, ZihengSun commented on docs/host.md
> +2. Change the desired fields.
```suggestion
2. Change the field values as you wish. 
Note: The Host Id is not editable. 
```

2022-01-12 22:21 UTC, ZihengSun commented on docs/host.md
> +3. Click the same edit icon as the first step. The changes have now been updated.
No need to click the edit button every time. Once you finish, click any place outside the text fields will trigger the save action. It is listening to the focus event.

2022-01-14 21:48 UTC, uhhmed commented on docs/host.md
An additional step is added to mention how to get here.

2022-01-14 21:49 UTC, uhhmed commented on docs/host.md
> +2. Input the `Host User Password` of your account on the server in the shown dialog pop up.
A note has been added at every occurrence of password input in all sections with a link to the password instructions in readme.md

2022-01-14 21:50 UTC, uhhmed commented on docs/host.md
> +3. An "Environment List" section will appear below the "Host Details" section showing all the available python environments on the connected server.
A "PyEnv" explicit callout has been added.

2022-01-14 21:51 UTC, uhhmed commented on docs/host.md
> +1. Click the second icon from the right (next to the red minus button) in the "Host Details" page.
An additional step is added to mention how to get here.

2022-01-14 21:51 UTC, uhhmed commented on docs/host.md
> +2. Input the `Host User Password` of your account on the server in the shown dialog pop up.
An additional step is added to mention how to get here.

2022-01-14 21:52 UTC, uhhmed commented on docs/host.md
> +3. Click Confirm.
Expanded the last step to mention the appropriate section appearing when the function executes correctly

2022-01-14 21:53 UTC, uhhmed commented on docs/host.md
> +2. Input the `Host Password` of your account on the server in the shown dialog pop up.
A note has been added at every occurrence of password input in all sections with a link to the password instructions in readme.md

2022-01-14 21:53 UTC, uhhmed commented on docs/host.md
> +3. A file upload section will appear below the "Host Details" section with drag and drop or file browser capability.
A screenshot has been added and uploaded.

2022-01-14 21:54 UTC, uhhmed commented on docs/host.md
> +5. A progress bar with a status above will indicate the progress of the upload.
Additional step is added to mention what happens when the upload is complete and where the file is.

2022-01-14 21:55 UTC, uhhmed commented on docs/host.md
> +3. Click the same edit icon as the first step. The changes have now been updated.
This doesn't work with me. if i click outside any of the fields, or even the right panel, nothing happens. only when the edit icon is clicked is when the values are actually updated.

2022-01-15 04:55 UTC, ZihengSun commented on docs/host.md
> +1. Click the edit icon (first icon) at the bottom right corner of the "Host Details" page.
```suggestion
1. Click the edit icon (first icon) in the `Host Details` page.
```

2022-01-15 04:56 UTC, ZihengSun commented on docs/host.md
> +3. Click the same edit icon as the first step. The changes have now been updated.
```suggestion
3. Click the edit icon button again. The changes should be updated.
```

2022-01-15 05:20 UTC, ZihengSun commented on docs/host.md
> +3. Click the same edit icon as the first step. The changes have now been updated.
That is how the fields in process/workflow pages work. It is fine. Just describe how it works in Host page.

2022-01-15 05:21 UTC, ZihengSun commented on docs/host.md
> +3. An "Environment List" section will appear below the "Host Details" section showing all the available PyEnv python environments on the connected server.
```suggestion
3. An `Environment List` section will appear below the `Host Details` section showing all the available PyEnv python environments on the connected server.
```

2022-01-15 05:21 UTC, ZihengSun requested changes
Change all " to `

2022-01-17 16:19 UTC, merged