Update index.md
ZihengSun/Geoweaver pull request #72
Opened 2023-02-09 19:25 UTC by Bhargavijanga58

2023-02-09 20:44 UTC, ZihengSun requested changes
look good and minor comment

2023-02-09 20:44 UTC, ZihengSun commented on docs/index.md
> -# [Tutorial](https://zihengsun.github.io/Geoweaver/)
why remove this link?

2023-02-09 20:52 UTC, Bhargavijanga58 commented on docs/index.md
> -# [Tutorial](https://zihengsun.github.io/Geoweaver/)
As it is redirecting to the same webpage, below we have links to follow up on the tutorial, that is the reason I made it as a heading. Kindly let me know if I am wrong.

2023-02-09 23:40 UTC, ZihengSun commented on docs/host.md
> +
why adding so many empty lines?

2023-02-09 23:42 UTC, ZihengSun commented on docs/index.md
> -# [Tutorial](https://zihengsun.github.io/Geoweaver/)
Actually not really. This markdown is only available in GitHub which is not the same link. The link `https://zihengsun.github.io/Geoweaver/` is generated using mkdocs and published in another branch.

2023-02-09 23:46 UTC, Bhargavijanga58 commented on docs/index.md
> -# [Tutorial](https://zihengsun.github.io/Geoweaver/)
Okay professor. I will undo that change.

2023-02-10 00:07 UTC, Bhargavijanga58 commented on docs/host.md
> +
I was using a software to edit and it added spaces. I will make sure not to repeat the same.

2023-02-10 03:15 UTC, ZihengSun commented on docs/install.md
> +    `docker run -t -i -v <YOUR_HOME_DIRECTORY>:/home/marsvegan/ -p 8070:8070 jensensun/geoweaver`
this space makes the command not rendered correctly in GitHub. can you double check in Github after every commit? make sure it appears the same as in your local software.

2023-02-10 03:16 UTC, ZihengSun commented on docs/install.md
> +    `alias geoweaver="docker run -t -i -v <YOUR_HOME_DIRECTORY>:/home/marsvegan/ -p 8070:8070 jensensun/geoweaver"`
same here. can you just change markdown directly in text? don't use third party software. The auto formatting is a bit annoying.

2023-02-10 03:22 UTC, ZihengSun commented on docs/host.md
> +>  `Note`: if the selected server is localhost, password instructions are discussed [here](#install.md)
this link doesn't work for some reason, double check

2023-02-10 03:28 UTC, ZihengSun commented on docs/host.md
>  ![Screen Shot 2022-01-15 at 12 39 12 AM](https://user-images.githubusercontent.com/34227630/149588755-f1982927-a2b0-453f-8248-65fc5668428c.png)
We intend to NOT include screenshots in the tutorial, as our GUI is changing all the time. Also the link seems to be temporary and not sure if it is a permanent link. Please remove.

2023-02-11 14:07 UTC, merged